### ISSUE TITLE
Display Username on delete card action in activity window

### ISSUE THREAD

**Issue by ayushagg31** [ayushagg31/Trellis#11]
![image](https://user-images.githubusercontent.com/17214678/95212160-08c93a80-080b-11eb-8c9b-e4f2d5a3ba23.png)

**Comment by ColinFrick** [comment]
Hi there. I'd like to look into this

**Comment by ayushagg31** [comment]
Sure, let me know if you need some help. Also, watch out for contributor guidelines, I'll be putting it up soon.
