### ISSUE TITLE
Add Load More Button instead of displaying all activities at once on the activity window

### ISSUE THREAD

**Issue by ayushagg31** [ayushagg31/Trellis#12]

**Comment by Anu9518** [comment]
I would like to give a shot. Please assign me to this.

**Comment by ayushagg31** [comment]
Good Luck @Anu9518

**Comment by ayushagg31** [comment]
@Anu9518 , Issue has been unassigned due to inactivity. Please comment, if you're still working on the issue.

**Comment by ColinFrick** [comment]
I'd like to work on this task.
