### ISSUE TITLE
Setup the eslint for whole project

### ISSUE THREAD

**Issue by ayushagg31** [ayushagg31/Trellis#26]
- [ ] Setup eslint for React app
- [ ] Create .eslintrc file
- [ ] Add rule set, I'll be providing few rule set soon
- [ ] Update Package.json with lint (initialize eslint for the project) and lint-fix (fix the linting issues)

Note - Submit your changes to develop branch for now. I'll be reviewing it on priority.

**Comment by ayushagg31** [comment]
Setup `.eslintrc.json` file with this configuration
```{
    "env": {
        "commonjs": true,
        "es2020": true,
        "node": true
    },
    "extends": "eslint:recommended",
    "parserOptions": {
        "ecmaVersion": 11
    },
    "rules": {
        "indent": [
            "error",
            4
        ],
        "linebreak-style": [
            "error",
            "windows"
        ],
        
        "quotes": [
            "error",
            "single"
        ],
        "semi": [
            "error",
            "never"
        ]
    }
}

**Comment by itamar244** [comment]
want to take this issue :)

**Comment by Bohemus307** [comment]
Still needed?

**Comment by ayushagg31** [comment]
A Pull Request is currently under review. Will close this issue if PR passes all the requirements.

**Comment by Bohemus307** [comment]
Id be happy to take a look.
