### ISSUE TITLE
Fixing typo in readme files

### ISSUE THREAD

**Issue by jacubsmith** [ayushagg31/Trellis#31]
### Overview Description
# Steps to Reproduce

1. Open README or CONTRIBUTING.
2. Scroll to the section explaining how to make a dev.env for development.
3. Wrong command specified.

# Actual Results
`mkdir dev.env` - which will create a directory.

# Expected Results
`touch dev.env` - which will create a file.

# Additional Information:
Have also added an `echo` command to populate the file.

**Comment by ayushagg31** [comment]
Thanks @jacubsmith for pointing out this mistake, although `touch` is a Linux specific command, so please create instruction for both windows and Linux seperately.

## Windows
```
cd ../config 
(
echo PORT=1313
echo DATABASE_URL="MongoDB Connection String"
echo JWT_SECRET="YOUR JWT TOKEN"
echo NODE_ENV=development
) > dev.env
```
