### ISSUE TITLE
Problem in logging in

### ISSUE THREAD

**Issue by harsh599** [ayushagg31/Trellis#39]
![image](https://user-images.githubusercontent.com/31313683/95616594-a6c93900-0a87-11eb-82af-829a220d2431.png)
 Please help errors are shown in console I have provided the unsplash api key.

**Comment by ayushagg31** [comment]
can you share the steps you followed to launch the website?

**Comment by harsh599** [comment]
I followed all steps you mentioned. I think I have some difficulty at point 3. & 4. At point 3 I  have mentioned the unsplash api key
![image](https://user-images.githubusercontent.com/31313683/95646185-87f89000-0ae3-11eb-9a39-36ecf63cc18a.png)
 and at step 4 i didnt get how to accomplish it kindly help

**Comment by ayushagg31** [comment]
You don't really need Unsplash API key, if you are not working on issue related to images. In order to launch the project you only need to create `dev.env` file inside config folder. Add below text in there -
```
PORT=1313 // your server port
DATABASE_URL="MongoDB Connection String" // mention your monogoDB string
JWT_SECRET="YOUR JWT TOKEN"  // mention your sample JWT token
NODE_ENV=development
```
Let me know if you're still facing any issues.
