### ISSUE TITLE
Create react app eslint config not working

### ISSUE THREAD

**Issue by ayushagg31** [ayushagg31/Trellis#42]
**Describe the bug**
CRA provides ESLint rules with it, but due to some reasons, it's not suggesting about warning/errors.

**To Reproduce**
1. Run Project
2. Go to Trellis home page
3. Now you'll see some warnings related to **eslint-config-react-app**

**Screenshots**
![image](https://user-images.githubusercontent.com/17214678/95624680-e34f6180-0a94-11eb-9711-f97cfa196921.png)

**Probable Causes**
- Some eslint dependencies are not installed
- Existing dependencies are not compatible with CRA

**Comment by Toshiuk** [comment]
Assign?

**Comment by Toshiuk** [comment]
Here is the PR https://github.com/ayushagg31/Trellis/pull/43

**Comment by ayushagg31** [comment]
sure, I'll take a look.
