### ISSUE TITLE
I should be able to create new lists and cards by hitting the "enter" key instead of having to press the button every time

### ISSUE THREAD

**Issue by jeffslofish** [ayushagg31/Trellis#46]
**Is your feature request related to a problem? Please describe.**
I am frustrated when I am trying to quickly create new lists and cards and I have to move my hands from the keyboard to the mouse to click the button to add a new list or card.

**Describe the solution you'd like**
 It would be great if instead of creating a new line, pressing enter would just create the list or card as if I pushed the button. This is how Trello works as well.

I can work on this if you assign it to me

**Comment by ayushagg31** [comment]
Haha, I was planning to implement this one, you can go ahead.
