### ISSUE TITLE
There should be a confirmation dialog before a board, list, or card is deleted

### ISSUE THREAD

**Issue by jeffslofish** [ayushagg31/Trellis#48]
**Is your feature request related to a problem? Please describe.**
It is possible to accidentally hit the delete button for a board, list, or card. It would be nice if the item wasn't immediately deleted when the button is pressed, but instead, a confirmation dialog is shown.

**Describe the solution you'd like**
I want a confirmation dialog to appear after clicking a delete icon for a board, list, or card. After pressing a "conform delete" button on the dialog, only then would the item be deleted.

**Describe alternatives you've considered**
Instead of a delete button with a confirmation dialog, there could instead just be an "archive" button that doesn't permanently delete the item. Additional functionality would have to be added to recover an archived item.

**Comment by ayushagg31** [comment]
I believe issue #8 and #10 are somewhat related to what you mentioned. Also confirmation dialog for every delete action can be very annoying for the user if he/she were to delete multiple items at once, so undo/archive option is much better.
Let me know what are your thoughts on this.

**Comment by elmehdibm** [comment]
I want to take this issue , please assign it to me :)

**Comment by ayushagg31** [comment]
Hi @elmehdibm, this is a duplicate issue, they have been assigned already. See #8 and #10

**Comment by elmehdibm** [comment]
Ah I see thank you for your response , I'll explore other new issues to work on 😁 , I'll be glad if you suggest me some issue to work on 🙏 , thanks in advance

**Comment by ayushagg31** [comment]
Give issue #37 a try, it's currently unassigned.

**Comment by elmehdibm** [comment]
thank you a lot

**Comment by jeffslofish** [comment]
Yes, I changed my mind. An undo/archive option is better.
