### ISSUE TITLE
Add workflow for linter check in PR's

### ISSUE THREAD

**Issue by ayushagg31** [ayushagg31/Trellis#52]
To make sure that the code in the master branch has the proper style, we need to put in place a basic pipeline, using GitHub Actions, for running linting checks on the javascript code

**Comment by jacubsmith** [comment]
Happy to take this one

**Comment by jacubsmith** [comment]
@ayushagg31 how do you feel about adding a pre commit lint check as well?

**Comment by ayushagg31** [comment]
Yeah, git precommit hook will be better idea, give this a shot.

**Comment by jacubsmith** [comment]
Have added it as a workflow and explained my reasoning in the PR - if you agree the next step would be issue #54  and then we can add it in as a pre-commit as well.
