### ISSUE TITLE
Addink redux-thunk to manipulate the aplication state

### ISSUE THREAD

**Issue by Any28Flo** [ayushagg31/Trellis#7]
What do yo think about add  [https://github.com/reduxjs/redux-thunk](redux-thunk) to manipulate the aplication state

**Comment by ayushagg31** [comment]
Yep, I am using redux-thunk already in the project, here's the [store file](https://github.com/ayushagg31/Trellis/blob/master/client/src/store/configureStore.js), where I am configuring it. I am not sure, if that's what you're referring to.
