### ISSUE TITLE
Create a warning pop-up when user is deleting a board

### ISSUE THREAD

**Issue by ayushagg31** [ayushagg31/Trellis#8]

**Comment by liamortiz** [comment]
Hello I'm going to give this one a shot !

**Comment by ayushagg31** [comment]
Sure, let me know if you need some help. Also, watch out for contributor guidelines, I'll be putting it up soon.

**Comment by Lutheriel** [comment]
Hello, is this issue open? Can I work on this issue? :)

**Comment by ayushagg31** [comment]
Hi @Lutheriel, this issue is taken, please checkout other issues, or feel free to open new issues if you found any.

**Comment by ColinFrick** [comment]
I'd like to work on this task
