### ISSUE TITLE
Improve Readme  and add file structure information to make it more open-source friendly

### ISSUE THREAD

**Issue by ayushagg31** [ayushagg31/Trellis#9]

**Comment by JoshuaPCruz** [comment]
I would like to do this, I love markup, can you assign it to me?

**Comment by ayushagg31** [comment]
Hi @JoshuaPCruz, as I can see you are interested in two issues, but I recommend you to take up one issue at a time, once submitted you can move on to next issue. I'll assign this issue for now. Let me know if you need any help.

**Comment by JoshuaPCruz** [comment]
Hi,
no problem at all, thanks
